name: Build

on:
  pull_request:
    branches:
      - "1.0-develop"

jobs:
  ui:
    name: UI
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        node-version: [ 22 ]
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - run: yarn tsc
      - run: yarn lint
      - run: yarn build:production

  helper-plugin:
    name: Helper plugin
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Test and build the plugin
        working-directory: helper-plugin
        run: |
          chmod +x gradlew
          ./gradlew --no-daemon test shadowJar
